### ISSUE TITLE
Gurobi addconstr! only adds constraint in solver, but not in GurobiMathProgModel

### ISSUE THREAD

**Issue by skipperafrosenborg** [JuliaOpt/Gurobi.jl#117]
I'm fairly new to the whole JuMP/MathProgBase modelling environment and I, therefore, might have misunderstood the whole architecture which might be the main problem.

My problem is:
When I add constraints it seems like they are only added in the Gurobi Solver and not in the GurobiMathProgModel. 
How can I update my GurobiMathProgModel after I added the constraints?

My process is the following:
1.  I build a JuMP model (as it is the easiest way to model) and convert it to a GurobiMathProgModel, as I need to change the coefficients later in the script.
2. I then later need to add additional constraints to my problem and send this GurobiMathProgModel to different functions in my script. 

I put some example code below that reflects my problem. 
I hope you can help me or explain how I should actually use the architecture. 
```julia
m = Model(solver = GurobiSolver())

#Add binary variables to JuMP model
@variable(m, 0 <= z[1:nCols] <= 1, Bin )

#Define objective function
@objective(m, Max, sum(z[i] for i=1:length(z)))

#Build model
JuMP.build(m)

#Convert to GurobiMathProgModel
m2 = internalmodel(m)

#Try to add constraint
Gurobi.addconstr!(m2, [1], [1], -Inf, 2)

#Updating model
Gurobi.updatemodel!(m2)

#Output GurobiMathProgModel to check number of constraints in the model
m2     #Output 0 constraints

#Get raw solver to check number of constraints
Gurobi.getrawsolver(m2) #Output 1 constraint
```

**Comment by joehuchette** [comment]
@skipperafrosenborg in JuMP you have models at the JuMP, MathProgBase, and Gurobi levels (from high to low), and when adding constraints to your model they will only propagate downwards. This is why you aren't seeing constraints added at the Gurobi level appear in JuMP or MathProgBase.

Can you add all constraints at the JuMP level, and then change coefficients as-needed by dropping down to the Gurobi level? That seems like the simplest approach.

**Comment by skipperafrosenborg** [comment]
@joehuchette Thanks a lot for the quick reply. I think I understand it now. 

It's a great idea to add all the constraints and just change the coefficients. 

Cheers for the help! Should I close or delete this issue now, or how does it work?

**Comment by joehuchette** [comment]
Glad to help! I'll close it. 

In the future, these types of usage questions are best directed to the [discourse page](https://discourse.julialang.org/c/domain/opt); Github issues are typically intended for bug reports or feature requests.

**Comment by skipperafrosenborg** [comment]
Ahh, sorry about that. I'll direct future questions there. 

Thanks for the help though!
