### ISSUE TITLE
get_basis limit issue

### ISSUE THREAD

**Issue by Thuener** [JuliaOpt/Gurobi.jl#120]
I think there is a bug with function `get_basis(model::Model)`. It is not accounting for slack variables, the limit shouldn't be `num_vars(model)` but the number of lines of A matrix. After, it has to use `GRBgetBasisHead` to know the corresponding variables and known which variables are slacks. I will try to submit pull request soon.

**Comment by odow** [comment]
It doesn't look like this was ever tested. Maybe you could add some tests as well?

**Comment by Thuener** [comment]
I will

**Comment by Thuener** [comment]
I think it was a confusion with the name of the function. This function doesn't get the basis, it get wich of the original variables in cbasis and for slack variables in rbasis are in base or not. When I was using advanced functions like GRBBinvRowi it was confusing. If you want I have a test case for this function using Complementary Slackness, otherwise I will close this issue.
