### ISSUE TITLE
Gurobi is not working

### ISSUE THREAD

**Issue by stumarcus576** [JuliaOpt/Gurobi.jl#132]
I get the following error when I try to create the Gurobi environment:

Capacity available on '10.60.129.38' - connecting...
Established 256-bit AES encrypted connection
ERROR: LoadError: Failed to create environment (error 10022).
Stacktrace:
 [1] Gurobi.Env() at /Users/a598124/.julia/v0.6/Gurobi/src/grb_env.jl:15
 [2] include_from_node1(::String) at ./loading.jl:576
 [3] include(::String) at ./sysimg.jl:14
 [4] process_options(::Base.JLOptions) at ./client.jl:305
 [5] _start() at ./client.jl:371
while loading /Users/a598124/juliaCode/pre2/bee.jl, in expression starting on line 127

**Comment by odow** [comment]
Are you somehow trying to use the Gurobi cloud?

For a discussion, see the PR: https://github.com/JuliaOpt/Gurobi.jl/pull/54

**Comment by odow** [comment]
The error 10022 is a network error. See http://www.gurobi.com/documentation/8.0/refman/cs_constants.html

It looks like it is a problem with your cluster.

**Comment by stumarcus576** [comment]
Yes, there is an office network communication problem with the cluster. Thanks.
