### ISSUE TITLE
`NaN` solution when MIP solution hits the time limit (via LinQuadOptInterface)

### ISSUE THREAD

**Issue by rdeits** [JuliaOpt/Gurobi.jl#140]
When an MIP hits its time limit before reaching optimality, we return `MOI.UnknownResultStatus` for both the primal and dual status of the problem. However, it's often the case that at least one feasible solution has been found before the time limit, but the user can't retrieve this solution because LQOI sees the primal UnknownResultStatus and doesn't extract the primal solution. Instead, when we reach the time limit, I think we should ask Gurobi if it has a feasible solution and return `FeasiblePoint` for the primal status if so. 

Does that seem reasonable?

**Comment by mlubin** [comment]
Absolutely, this was one of the major motivations for redoing the status-reporting API.

**Comment by rdeits** [comment]
Ok, great. I'll give it a shot. I'm currently trying to figure out what the right attribute to query would be. Newer Gurobi versions have `SolCount` which should be > 0 when a feasible solution exists, but I don't want to break older Gurobi versions. I *think* it should be safe to check if the MIP gap is finite (or, in Gurobi-land, not equal to `1e100`).

**Comment by rdeits** [comment]
Oh, actually, SolCount goes back to 7.0, which is the oldest version available for download and the oldest version for which Gurobi posts documentation. So I think I'll just use that.
