### ISSUE TITLE
Update for Julia v1.0

### ISSUE THREAD

**Issue by LaughMachine** [JuliaOpt/Gurobi.jl#147]
Is there a version of Gurobi for Julia version 1.0? Currently, building Gurobi on Julia runs into an error:

> Building Gurobi → `~/.julia/packages/Gurobi/dkBsF/deps/build.log`
> ┌ Error: Error building `Gurobi`:
> │ ERROR: LoadError: UndefVarError: is_apple not defined
> │ Stacktrace:
> │  [1] top-level scope at /Users/michaelhuang/.julia/packages/Gurobi/dkBsF/deps/build.jl:26 [inlined]
> │  [2] top-level scope at ./none:0
> │  [3] include at ./boot.jl:317 [inlined]
> │  [4] include_relative(::Module, ::String) at ./loading.jl:1038
> │  [5] include(::Module, ::String) at ./sysimg.jl:29
> │  [6] include(::String) at ./client.jl:388
> │  [7] top-level scope at none:0
> │ in expression starting at /Users/michaelhuang/.julia/packages/Gurobi/dkBsF/deps/build.jl:16
> └ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068
> 

This can be solved by changing is_apple() to isapple(). The same can be done for is_windows() and is_unix().

**Comment by odow** [comment]
Gurobi.jl has not been updated for v1.0. PRs are gladly accepted :)

**Comment by rdeits** [comment]
The particular issue mentioned here will be fixed in #148, but I haven't yet run the Gurobi tests on Julia 1.0. So @LaughMachine if you find additional issues please feel free to open them.

**Comment by LaughMachine** [comment]
Thanks for following up guys! @rdeits So far I've only gotten as far as building the module. The other issues I've noticed are:

1. In build.jl, the variables defined outside the scope of for loops are not being passed into the for loop. For example, in lines 31-39 the variable "found" defined in line 31 will always be false since the variable found in line 35 only exists in the scope of the for loop. My fix was to add the line "global found" inside the for loop, but I'm still trying to understand the changes in Julia 1.0 so I'm not entirely sure that is the right thing to do. 

`found = false
for l in paths_to_try
    d = Libdl.dlopen_e(l)
    if d != C_NULL
        found = true
        write_depsfile(l)
        break
    end
end`

2. It also seems necessary to import the Libdl module, so including "using Libdl" seems necessary for build.jl

3. In Gurobi.jl, I think "importall" is deprecated so I changed it to "using", but I'm not sure this is the right thing to do as well.

After making these changes I was able to successfully build the module.

**Comment by rdeits** [comment]
Thank you, that's very helpful. Please open a PR with the changes you've made so far. Even if they're not finished, we can help you clean it all up. Also, from your github history it looks like you're new here, so welcome! Please let me know if you want help opening a pull request (PR).
