### ISSUE TITLE
New release? 

### ISSUE THREAD

**Issue by rdeits** [JuliaOpt/Gurobi.jl#149]
It would be very useful to have a released version that supports LQOI 0.3 and MOI 0.5. Could you make a new tag?

**Comment by mlubin** [comment]
Go ahead, you have permission :)
Please double check that tests are passing locally since we don't have CI.

**Comment by rdeits** [comment]
Ok, will do. With MathOptInterface v0.5.1 and LinQuadOptInterface v0.3.0, I have:

```
INFO: Gurobi tests passed
```
