### ISSUE TITLE
large performance regression in calling `JuMP.build` using `MathProgBase` in 1.0

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaOpt/Gurobi.jl#152]
In my case from a few seconds to almost 2 minutes.  I know it's coming from the call to `JuMP.build` on the model, but I don't know where yet.

Sorry for the lack of details, will look into it as soon as I get the chance, wanted to open this issue to keep track.

**Comment by ExpandingMan** [comment]
Ok, first update it seems to be slow on `MathProgBase.loadproblem!` which happens in JuMP [solvers.jl](https://github.com/JuliaOpt/JuMP.jl/blob/release-0.18/src/solvers.jl#L372) line 372.

**Comment by odow** [comment]
That's weird because very little has changed in Gurobi.jl with respect to MathProgBase. However, there are [known performance issues with LQOI](https://github.com/JuliaOpt/LinQuadOptInterface.jl/issues/51) using Gurobi via MOI at the moment.

**Comment by ExpandingMan** [comment]
Ok, finally traced this down and the result is a bit scary.

The regression is due to a call of `sparse(transpose(A))` [here](https://github.com/JuliaOpt/Gurobi.jl/blob/master/src/grb_constrs.jl#L81).  This regression apparently scales very badly with the size of the matrix, which in my case is `(97864, 161284)`.

The function call in question is in `SparseArrays` in `sparsematrix.jl` somewhere in the call to `SparseMatrixCSC` at line 374.

At first glance I'm not at all sure about what to do as a work-around, but we'll definitely need something or this will never work for large problems in 1.0.

**Comment by ExpandingMan** [comment]
Ah, so happy there is a simple fix!  This could have been quite the headache to fix.  PR incoming.

**Comment by ExpandingMan** [comment]
Will be fixed by #153
