### ISSUE TITLE
Gurobi 8.0 problem

### ISSUE THREAD

**Issue by CBongiova** [JuliaOpt/Gurobi.jl#159]
Hello, 

I have just installed Gurobi 8.0 and tried to solve an MILP with an Informational callback function. 
After solving, though I get the following error message:

<img width="1003" alt="screen shot 2018-09-25 at 13 10 41" src="https://user-images.githubusercontent.com/24223801/46010884-755dba80-c0c4-11e8-9287-0323d80fbb36.png">

Does anyone know what this issue is to due and have hints on how to fix it?

**Comment by odow** [comment]
Please provide a reproducible example that we can run, demonstrating the problem.

**Comment by CBongiova** [comment]
You can actually run any MILP which includes an informational callback and/or lazy constraints. For example, see the MILP proposed under the lazy constraints in the Solver Callbacks page at https://jump.readthedocs.io/en/latest/callbacks.html 

That is: 

using JuMP
using Gurobi

# We will use Gurobi
m = Model(solver=GurobiSolver())

# Define our variables to be inside a box, and integer
@variable(m, 0 <= x <= 2, Int)
@variable(m, 0 <= y <= 2, Int)

@objective(m, Max, y)

# We now define our callback function that takes one argument,
# the callback handle. Note that we can access m, x, and y because
# this function is defined inside the same scope
function corners(cb)
    x_val = getvalue(x)
    y_val = getvalue(y)
    println("In callback function, x=$x_val, y=$y_val")

    # We have two constraints, one cutting off the top
    # left corner and one cutting off the top right corner, e.g.
    # (0,2) +---+---+ (2,2)
    #       |xx/ \xx|
    #       |x/   \x|
    #       |/     \|
    #       +       +
    #       |       |
    #       |       |
    #       |       |
    # (0,0) +---+---+ (2,0)

    # Allow for some impreciseness in the solution
    TOL = 1e-6

    # Check top left, allowing some tolerance
    if y_val - x_val > 1 + TOL
        # Cut off this solution
        println("Solution was in top left, cut it off")
        # Use the original variables, but not m - cb instead
        @lazyconstraint(cb, y - x <= 1)
    # Check top right
    elseif y_val + x_val > 3 + TOL
        # Cut off this solution
        println("Solution was in top right, cut it off")
        # Use the original variables, but not m - cb instead
        @lazyconstraint(cb, y + x <= 3)
    end
end  # End of callback function

# Tell JuMP/Gurobi to use our callback function
addlazycallback(m, corners)


solve(m)

# Print our final solution
println("Final solution: [ $(getvalue(x)), $(getvalue(y)) ]")

The error I get in the console is: 
<img width="960" alt="screen shot 2018-09-25 at 16 46 31" src="https://user-images.githubusercontent.com/24223801/46022278-97fecc00-c0e2-11e8-8df5-b04efc277e95.png">

**Comment by odow** [comment]
I have not tried, my v0.6 installation is a little out of kilter recently.

**Comment by CBongiova** [comment]
@odow Sorry to bother you again but I couldn't find a solution to the problem myself. 
Again, with the simple code I have posted above, I get the following error message: 

> MethodError: no method matching cbgetstate(::Gurobi.GurobiCallbackData)[0m
Closest candidates are:
  cbgetstate([91m::MathProgBase.SolverInterface.LPQPWrapperCallbackData[39m) at /Users/admin/.julia/v0.6/MathProgBase/src/SolverInterface/lpqp_to_conic.jl:323
  cbgetstate([91m::Int64[39m) at /Users/admin/.julia/v0.6/MathProgBase/src/SolverInterface/SolverInterface.jl:29
  cbgetstate() at /Users/admin/.julia/v0.6/MathProgBase/src/SolverInterface/SolverInterface.jl:27
lazycallback(::Gurobi.GurobiCallbackData, ::JuMP.Model, ::Array{JuMP.LazyCallback,1}) at callbacks.jl:63
(::JuMP.##156#157{JuMP.Model,Array{JuMP.LazyCallback,1}})(::Gurobi.GurobiCallbackData) at callbacks.jl:96
mastercallback(::Ptr{Void}, ::Ptr{Void}, ::Int32, ::Ptr{Void}) at MPBWrapper.jl:716
optimize(::Gurobi.Model) at grb_solve.jl:5
optimize!(::Gurobi.GurobiMathProgModel) at MPBWrapper.jl:428
#solve#132(::Bool, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::JuMP.Model) at solvers.jl:175
solve(::JuMP.Model) at solvers.jl:150
include_string(::String, ::String) at loading.jl:522
include_string(::String, ::String, ::Int64) at eval.jl:30
include_string(::Module, ::String, ::String, ::Int64, ::Vararg{Int64,N} where N) at eval.jl:34
(::Atom.##102#107{String,Int64,String})() at eval.jl:82
withpath(::Atom.##102#107{String,Int64,String}, ::String) at utils.jl:30
withpath(::Function, ::String) at eval.jl:38
hideprompt(::Atom.##101#106{String,Int64,String}) at repl.jl:67
macro expansion at eval.jl:80 [inlined]
(::Atom.##100#105{Dict{String,Any}})() at task.jl:80

**Comment by chriscoey** [comment]
I am having the same issue on julia 0.6.4 on ubuntu, and I know a student at the ORC who was having this issue also. I am using the latest releases of Gurobi, JuMP, MPB.

```
ERROR: LoadError: MethodError: no method matching cbgetstate(::Gurobi.GurobiCallbackData)
Closest candidates are:
  cbgetstate(::MathProgBase.SolverInterface.LPQPWrapperCallbackData) at /home/coey/.julia/v0.6/MathProgBase/src/SolverInterface/lpqp_to_conic.jl:323
  cbgetstate(::Int64) at /home/coey/.julia/v0.6/MathProgBase/src/SolverInterface/SolverInterface.jl:29
  cbgetstate() at /home/coey/.julia/v0.6/MathProgBase/src/SolverInterface/SolverInterface.jl:27
Stacktrace:
 [1] lazycallback(::Gurobi.GurobiCallbackData, ::JuMP.Model, ::Array{JuMP.LazyCallback,1}) at /home/coey/.julia/v0.6/JuMP/src/callbacks.jl:63
 [2] (::JuMP.##156#157{JuMP.Model,Array{JuMP.LazyCallback,1}})(::Gurobi.GurobiCallbackData) at /home/coey/.julia/v0.6/JuMP/src/callbacks.jl:96
 [3] mastercallback(::Ptr{Void}, ::Ptr{Void}, ::Int32, ::Ptr{Void}) at /home/coey/.julia/v0.6/Gurobi/src/MPBWrapper.jl:706
 [4] optimize(::Gurobi.Model) at /home/coey/.julia/v0.6/Gurobi/src/grb_solve.jl:5
 [5] optimize!(::Gurobi.GurobiMathProgModel) at /home/coey/.julia/v0.6/Gurobi/src/MPBWrapper.jl:428
 [6] #solve#132(::Bool, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::JuMP.Model) at /home/coey/.julia/v0.6/JuMP/src/solvers.jl:175
 [7] (::JuMP.#kw##solve)(::Array{Any,1}, ::JuMP.#solve, ::JuMP.Model) at ./<missing>:0
```

**Comment by CBongiova** [comment]
I have tried to install Julia v.1.0 to see if the issue kind of solved itself...
Now, every time I run 

> using Gurobi 
I get the following message in the console 
> [ Info: Recompiling stale cache file /Users/admin/.julia/compiled/v1.0/Gurobi/do9v6.ji for Gurobi [2e9cd046-0924-5485-92f1-d5272153d98b]
And then the error message
> UndefVarError: is_windows not defined
getproperty at sysimg.jl:13 [inlined]
setmathprogcallback!(::Gurobi.GurobiMathProgModel) at MPBWrapper.jl:721
macro expansion at logging.jl:307 [inlined]
optimize!(::Gurobi.GurobiMathProgModel) at MPBWrapper.jl:420
#solve#119(::Bool, ::Bool, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Model) at solvers.jl:175
solve(::Model) at solvers.jl:150
top-level scope at none:0
include_string(::Module, ::String, ::String) at loading.jl:1005
include_string(::Module, ::String, ::String, ::Int64) at eval.jl:30
(::getfield(Atom, Symbol("##117#123")){String,Int64,String})() at eval.jl:94
withpath(::getfield(Atom, Symbol("##117#123")){String,Int64,String}, ::String) at utils.jl:30
withpath at eval.jl:46 [inlined]
#116 at eval.jl:93 [inlined]
with_logstate(::getfield(Atom, Symbol("##116#122")){String,Int64,String}, ::Base.CoreLogging.LogState) at logging.jl:397
with_logger at logging.jl:493 [inlined]
#115 at eval.jl:92 [inlined]
hideprompt(::getfield(Atom, Symbol("##115#121")){String,Int64,String}) at repl.jl:85
macro expansion at eval.jl:91 [inlined]
(::getfield(Atom, Symbol("##114#120")){Dict{String,Any}})() at task.jl:85

@odow could you please help with v.1.0?
