### ISSUE TITLE
Gurobi package can not be build for Gurobi v8.1

### ISSUE THREAD

**Issue by tkosaka1976** [JuliaOpt/Gurobi.jl#169]
I installed v8.1 and surely confirmed the license.
However, Gurobi package v0.5.5 did not work well.
Especially on the building step.
I also set "export GUROBI_HOME=/Library/gurobi810/mac64"

>   Building Gurobi → `~/.julia/packages/Gurobi/YgG0A/deps/build.log`
> ┌ Error: Error building `Gurobi`:
> │ ERROR: LoadError: Unable to locate Gurobi installation. Note that this must be downloaded separately from gurobi.com
> │ Stacktrace:
> │  [1] error(::String) at ./error.jl:33
> │  [2] top-level scope at /Users/kousaka_tomoyuki/.julia/packages/Gurobi/YgG0A/deps/build.jl:47
> │  [3] include at ./boot.jl:317 [inlined]
> │  [4] include_relative(::Module, ::String) at ./loading.jl:1041
> │  [5] include(::Module, ::String) at ./sysimg.jl:29
> │  [6] include(::String) at ./client.jl:388
> │  [7] top-level scope at none:0
> │ in expression starting at /Users/kousaka_tomoyuki/.julia/packages/Gurobi/YgG0A/deps/build.jl:46
> └ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1069

if I use 8.0.1 then work well.
Whats wrong with it?

**Comment by odow** [comment]
What files are in `/Library/gurobi810/mac64/lib/`?

Here is the line that dictates what you need to set `GUROBI_HOME` to
https://github.com/JuliaOpt/Gurobi.jl/blob/67eaa2377eb549ab0a5729ac025849c50ff9422d/deps/build.jl#L24

**Comment by tkosaka1976** [comment]
This is the files list in "/Library/gurobi810/mac64/lib/"

> libgurobi_stdc++.a
> libgurobi81_light.dylib
> libGurobiJni81.jnilib
> gurobi81.netstandard20.xml
> gurobi.jar
> python3.6
> python3.7
> gurobi81.netstandard20.dll
> gurobi.py
> rootcert.pem
> libgurobi_c++.a
> python2.7
> python3.5
> gurobi-javadoc.jar
> libgurobi_g++4.2.a
> libgurobi81.dylib

**Comment by wgthompson** [comment]
Having this exam issue

**Comment by odow** [comment]
I guess Gurobi no longer use `.so`...
https://github.com/JuliaOpt/Gurobi.jl/blob/67eaa2377eb549ab0a5729ac025849c50ff9422d/deps/build.jl#L30

Try adding the following lines to [`Gurobi/deps/build.jl`](https://github.com/JuliaOpt/Gurobi.jl/blob/master/deps/build.jl) and re-run `Pkg.build("Gurobi")`
```julia
if Compat.Sys.isunix()
    push!(paths_to_try, joinpath(ENV["GUROBI_HOME"],"lib",string("lib",a,".so")))
end
# ==============================
# Add this bit
if Compat.Sys.isapple()
    push!(paths_to_try, joinpath(ENV["GUROBI_HOME"], "lib", string("lib", a, ".dylib")))
end
# ==============================
```

**Comment by cheng8721** [comment]
Hi,

I have then same problem. Where did you run "export GUROBI_HOME=/Library/gurobi810/mac64" ?
