### ISSUE TITLE
Gurobi.jl v0.5.4 JuliaPro Unable to locate Gurobi installation 

### ISSUE THREAD

**Issue by devendrashelar7** [JuliaOpt/Gurobi.jl#177]
Hi,

I installed on MacBookPro, the software JuliaPro 1.0.2.1 which has pre-installed julia-client 0.7.10. 

I also installed separately Julia 1.0 and Gurobi 8.1.0, and downloaded its license file into the home directory. 

My environment variables are set in the .bash_profile file are as follows:
export GUROBI_HOME=/Library/gurobi810/mac64
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/Library/gurobi810/mac64/bin
export LD_LIBRARY_PATH="/Library/gurobi810/mac64/lib"

Still, I am unable to access Gurobi from JuliaPro. 

Pkg.status() yields
Status `~/.juliapro/environments/JuliaPro/Project.toml`
  [336ed68f] CSV v0.4.1
  [861a8166] Combinatorics v0.7.0
  [a93c6f00] DataFrames v0.14.1
  [aaf54ef3] DistributedArrays v0.5.1
  [2e9cd046] Gurobi v0.5.4
  [916415d5] Images v0.16.0
  [4138dd39] JLD v0.9.0
  [4076af6c] JuMP v0.18.4
  [d330b81b] PyPlot v2.6.3

ENV["GUROBI_HOME"] yields "/Library/gurobi810/mac64"
ENV["PATH"] yields "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/Library/gurobi810/mac64/bin"

Also tried Pkg.update("Gurobi"). It failed. Then, Pkg.rm("Gurobi") and Pkg.add("Gurobi") which also didn't help. 

When I try ENV["LD_LIBRARY_PATH"], it yields  KeyError: key "LD_LIBRARY_PATH" not found. 
Could this be the reason? But, I am setting the .bash_profile correctly, right?

**Comment by odow** [comment]
Why did `Pkg.update` fail? You need at least Gurobi v0.5.6 to install 8.1 on OSX. See https://github.com/JuliaOpt/Gurobi.jl/pull/170

**Comment by devendrashelar7** [comment]
Pkg.update("Gurobi") does not fail. It just doesn't update to v0.5.6.

This is the output of Pkg.update("Gurobi")
Updating registry at `~/.juliapro/registries/JuliaPro`
  Updating git-repo `https://pkg.juliacomputing.com/registry/JuliaPro`
 Resolving package versions...
  Updating `~/.juliapro/environments/JuliaPro/Project.toml`
 [no changes]
  Updating `~/.juliapro/environments/JuliaPro/Manifest.toml`
 [no changes]

**Comment by odow** [comment]
Glad you got it working. Closing as this isn't Gurobi.jl related.
