### ISSUE TITLE
MIQP

### ISSUE THREAD

**Issue by stumarcus576** [JuliaOpt/Gurobi.jl#181]
Is it possible to solve a MIQP through JuMP's interface to Gurobi? In general, Gurobi is able to solve certain MIQPs.

**Comment by odow** [comment]
Yes. Here is an example: https://github.com/JuliaOpt/JuMP.jl/blob/release-0.18/examples/qcp.jl

In future, questions like this are better asked on Discourse: https://discourse.julialang.org/c/domain/opt

**Comment by stumarcus576** [comment]
Thanks for the help. It worked.
