### ISSUE TITLE
Does the following function automatically solve the updated LP with a "warm start"? (ps. An LP is solved before calling this function.)

### ISSUE THREAD

**Issue by wen-chih** [JuliaOpt/Gurobi.jl#182]
```julia
# update RHS and solve LP
function updateAndSolve(model::Gurobi.Model, k::Int64, scale::Int64, numInput::Int64, numOutput::Int64, transDataMatrix::Matrix{Float64})

  # changing RHS of model
  Gurobi.set_dblattrarray!(model, "RHS", numInput + 1, numOutput, transDataMatrix[numInput+1:numInput+numOutput, k])
  # changing coefficients
  cind = find(transDataMatrix[1:numInput, k])
  vind = fill(scale+1, length(cind))
  vval = -transDataMatrix[cind, k]

  chgCoeffs!(model, length(cind), cind,  vind, vval)
  update_model!(model)

  # solving model
  optimize(model)

  return get_objval(model), tChgRHS, tSolving
end
```

**Comment by odow** [comment]
If you are using the simplex method, yes. If you are using barrier, no.

In general, just assume that if you call `optimize(model)` on a model that has already been solved, Gurobi will do the fastest thing.

p.s. in future you should ask questions like this on discourse: https://discourse.julialang.org/c/domain/opt. More people read that forum so your question may help others in the future.

**Comment by odow** [comment]
Closing as this doesn't seem to be an issue with the Gurobi.jl wrapper. Please re-open if that is not the case.
