### ISSUE TITLE
Fail to build Gurobi 8.1.0 in JuliaPro1.0.2.1

### ISSUE THREAD

**Issue by cheng8721** [JuliaOpt/Gurobi.jl#199]
I have installed Gurobi and set the license correctly. I have run Pkg.add("Gurobi"). I got an error when I run Pkg.build("Gurobi")
```
Building Gurobi → `~/.juliapro/packages/Gurobi/kaIvm/deps/build.log`
┌ Error: Error building `Gurobi`:
│ ERROR: LoadError: Unable to locate Gurobi installation. Note that this must be downloaded separately from gurobi.com
│ Stacktrace:
│  [1] error(::String) at /Applications/JuliaPro-1.0.2.1.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
│  [2] top-level scope at /Users/smartfm/.juliapro/packages/Gurobi/kaIvm/deps/build.jl:50
│  [3] include_relative(::Module, ::String) at /Applications/JuliaPro-1.0.2.1.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
│  [4] include(::Module, ::String) at /Applications/JuliaPro-1.0.2.1.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:? (repeats 2 times)
│  [5] top-level scope at none:0
│ in expression starting at /Users/smartfm/.juliapro/packages/Gurobi/kaIvm/deps/build.jl:49
└ @ Pkg.Operations /Users/vagrant/worker/juliapro-release-osx1011-0_6/build/tmp_julia/Julia-1.0.app/Contents/Resources/julia/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1119
```
I checked my files there is no Gurobi810 file in Library.

Can anyone help me out?  Thanks a lot.

**Comment by odow** [comment]
Please follow the installation instructions in the README: https://github.com/JuliaOpt/Gurobi.jl#installation

> Note that this must be downloaded separately from gurobi.com

Have you installed Gurobi from http://www.gurobi.com/?

**Comment by cheng8721** [comment]
Yes, I installed Gurobi from http://www.gurobi.com/. Where should I set GUROBI_HOME environmental variable. I tried to run it in JuliaPro, I got:
julia> export GUROBI_HOME=/Library/gurobi810/mac64
ERROR: syntax: "/" is not a unary operator
I run it in the terminal, I just got an empty command line:
username-MacBook-Pro:~ username$ export GUROBI_HOME=/Library/gurobi810/mac64
username-MacBook-Pro:~ username$

Thanks.

**Comment by odow** [comment]
```julia
julia> ENV["GUROBI_HOME"] = "/Library/gurobi810/mac64"

julia> import Pkg

julia> Pkg.build("Gurobi")
```

> I checked my files there is no Gurobi810 file in Library.

If this is true, then you should replace `"/Library/gurobi810/mac64"` with the correct path.

**Comment by cheng8721** [comment]
Problem solved. Thanks a lot.
