### ISSUE TITLE
Implement `MOI.Silent`

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/Gurobi.jl#203]
See http://www.juliaopt.org/MathOptInterface.jl/dev/apireference/

**Comment by currymj** [comment]
For anyone like me stumbling on this in Google, a workaround to silence Gurobi right now is to simply pass `OutputFlag=0` to the solver constructor, so:

```
Gurobi.Optimizer(OutputFlag=0)
```

or

```
with_optimizer(Gurobi.Optimizer; OutputFlag=0)
```
