### ISSUE TITLE
[MOI] Changing bounds etc invalidates stored solution

### ISSUE THREAD

**Issue by odow** [JuliaOpt/Gurobi.jl#209]
I tried to use Gurobi with https://github.com/lanl-ansi/Juniper.jl, and ran into this bug
```julia
using Gurobi
const MOI = Gurobi.MOI

model = Gurobi.Optimizer()
x = MOI.add_variable(model)
c = MOI.add_constraint(model, MOI.SingleVariable(x), MOI.GreaterThan(0.0))
MOI.set(model, MOI.ObjectiveFunction{MOI.SingleVariable}(), MOI.SingleVariable(x))
MOI.set(model, MOI.ObjectiveSense(), MOI.MIN_SENSE)
MOI.optimize!(model)

# Can query the objective value
MOI.get(model, MOI.ObjectiveValue())

# Change a variable bound. The change is cached for update
MOI.set(model, MOI.ConstraintSet(), c, MOI.GreaterThan(1.0))

# Calling `get` forces an update
MOI.get(model, MOI.ConstraintSet(), c)

# Invalidating the stored objective :(
MOI.get(model, MOI.ObjectiveValue())
```
Error is
```Julia
ERROR: Gurobi.GurobiError(10005, "Unable to retrieve attribute 'ObjVal'")
```

I'm not sure what we should do, probably cache the objective value. And maybe objective bound, etc? The primal and dual solutions get cached by LQOI after `optimize!`, so these aren't affected.

cc @ccoffrin @Wikunia

**Comment by ccoffrin** [comment]
I am thinking that gurobi’s semantics are reasonable and this is a bug in
juniper.  Thoughts @Wikunia <https://github.com/Wikunia>?

**Comment by Wikunia** [comment]
Sorry I currently don't get where you use Juniper :smile: 
Please correct me if I'm wrong: You define a model, solve it and then change a constraint which changes the model and therefore makes the objective value invalid.

**Comment by odow** [comment]
Closing in favor of https://github.com/lanl-ansi/Juniper.jl/issues/130
