### ISSUE TITLE
Obtaining duals of convex problem with second order cone constraints not possible using Gurobi optimizer

### ISSUE THREAD

**Issue by junglegobs** [JuliaOpt/Gurobi.jl#217]
I have a convex problem (which therefore should have duals) yet these don't seem to work. I can solve the problem just fine, but if I try to obtain the duals of a constraint I either get `NaN` or `AssertionError: dual >= 0.0`. Minimum working example below, I'm guessing it might be specific to Gurobi?

```julia
using JuMP
using Gurobi

m = Model(with_optimizer(Gurobi.Optimizer))

@variable(m, x >= 0)
@variable(m, y >= 0)
@variable(m, z >= 0)

@constraint(m, con1, x + y == 2)
@constraint(m, con2, x + y + z >= 0)
@constraint(m, con3, x^2 >= y^2 + z^2)

optimize!(m)

dual(con1)
dual(con2)
dual(con3)
```

**Comment by odow** [comment]
Gurobi will only compute duals for QCP problems if you pass `QCPDual=1`. See https://groups.google.com/d/msg/gurobi/hq6EvyT-mxs/hlVX3sTLAQAJ

This is fixed in the wrapper re-write. See https://github.com/JuliaOpt/Gurobi.jl/pull/216/commits/f164589b872dd394ce4170e8249cdf2218acaa4c
