### ISSUE TITLE
Invalid Gurobi license windows10

### ISSUE THREAD

**Issue by DiwasPaudel07** [JuliaOpt/Gurobi.jl#219]
using JuMP
using Gurobi
env = Gurobi.Env() 
model = Gurobi.Model(env,m,:minimize)
....
.....
....
...

Oputput:
Invalid Gurobi license

Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] Gurobi.Env() at C:\Users\Diwas'PC\.julia\packages\Gurobi\dlJep\src\grb_env.jl:13
 [3] top-level scope at In[3]:3

**Comment by odow** [comment]
Your gurobi license is invalid. Go to gurobi.com to get a new one.

This is not an issue with Gurobi.jl.

**Comment by odow** [comment]
Hi @DiwasPaudel07, How did you get on? Did you manage to fix the problem?

**Comment by odow** [comment]
Closing as stale. 

Please open a new thread on https://discourse.julialang.org/c/domain/opt if you still have problems.
