### ISSUE TITLE
DistributedMIPJobs and Workerpool

### ISSUE THREAD

**Issue by mstriebs** [JuliaOpt/Gurobi.jl#220]
I am not able to run distributed algorithms. Whenever i try to set the parameter "WorkerPool" as stated in the gurobi documentation I get the error "Unrecognized parameter name: WorkerPool." 

SolverSetting = with_optimizer(Gurobi.Optimizer,
    TimeLimit       = 100000,
    MIPGap          = 1*10^-5,
    DistributedMIPJobs = 2,
    WorkerPool = "_server_:_port_",
    )
Any Ideas?

**Comment by odow** [comment]
This file is probably out of date and needs to be updated with the latest parameters:
https://github.com/JuliaOpt/Gurobi.jl/blob/master/src/grb_params.jl

**Comment by mstriebs** [comment]
The stacktrace leads me to "[...].julia\packages\Gurobi\dlJep\src\grb_params.jl:325". When I add the entry "WorkerPool" to the constant GRB_STR_PARAMS and save the file it still fails with the same error message as before

**Comment by mstriebs** [comment]
got it. After adjusting the grb_params.jl I needed to restart the julia-session for the changes to be compiled. Thanks!!

**Comment by mlubin** [comment]
Reopening until the fix is merged in.
