### ISSUE TITLE
Gurobi.jl v0.6.0 "Unable to locate Gurobi installation" on Ubuntu

### ISSUE THREAD

**Issue by mao006006** [JuliaOpt/Gurobi.jl#221]
I have installed Julia 1.0.4, JuMP 0.18.5 and Gurobi solver 8.1. But cannot add Gurobi.jl in Julia. I got the following out when type "add Gurobi" in Julia,

(v1.0) pkg> add Gurobi
 Resolving package versions...
 Installed LinQuadOptInterface ─ v0.6.0
 Installed MathOptInterface ──── v0.8.4
 Installed Gurobi ────────────── v0.6.0
  Updating `~/.julia/environments/v1.0/Project.toml`
  [2e9cd046] + Gurobi v0.6.0
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [2e9cd046] + Gurobi v0.6.0
  [f8899e07] + LinQuadOptInterface v0.6.0
  [b8f27783] + MathOptInterface v0.8.4
  Building Gurobi → `~/.julia/packages/Gurobi/dlJep/deps/build.log`
┌ Error: Error building `Gurobi`: 
│ ERROR: LoadError: Unable to locate Gurobi installation. Note that this must be downloaded separately from gurobi.com
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at /home/ruizhang/.julia/packages/Gurobi/dlJep/deps/build.jl:62
│  [3] include at ./boot.jl:317 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1044
│  [5] include(::Module, ::String) at ./sysimg.jl:29
│  [6] include(::String) at ./client.jl:392
│  [7] top-level scope at none:0
│ in expression starting at /home/ruizhang/.julia/packages/Gurobi/dlJep/deps/build.jl:61
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1096

I did check the Env and it seems the path is set correctly.
julia> ENV["GUROBI_HOME"]
"/opt/gurobi810/linux64"

I have read all previous issues and followed the instructions there. I have reinstalled Julia, wiped the ~/.julia folder several times. No luck :(

I am sure the Gurobi solver 8.1 works properly on the machine. I have been using it with Python API for a while. I just want to switch to Julia. Any advice on what to do would be highly appreciated! Thank you!

**Comment by odow** [comment]
Can you copy the function from https://github.com/JuliaOpt/Gurobi.jl/pull/222/files, then run
```Julia
const ALIASES = [
    "gurobi81", "gurobi80",
    "gurobi75", "gurobi70"
]
diagnose_gurobi_install()
```
We should try to make the install process more user-friendly :)

**Comment by mao006006** [comment]
Thank you for your reply! I run the code and the output is:
julia> diagnose_gurobi_install()
Unable to locate Gurobi installation. Running some common diagnostics.

Gurobi.jl only supports the following versions:
 - gurobi81
 - gurobi80
 - gurobi75
 - gurobi70
Did you download and install one of these versions from gurobi.com?

Found GUROBI_HOME = /opt/gurobi810/linux64
Does this point to the correct install location?
- on Windows, this might be `C:\Program Files\gurobi810\win64\`
- alternatively, on Windows, this might be `C:/Program Files/gurobi810/win64/`
- on OSX, this might be `/Library/gurobi810/mac64/`
- on Unix, this might be `/opt/gurobi810/linux64/`


Here are the files we searched:
ERROR: SystemError: unable to read directory /opt/gurobi810/linux64/lib: No such file or directory
Stacktrace:
 [1] readdir(::String) at ./file.jl:620
 [2] diagnose_gurobi_install() at /home/ruizhang/1.jl:20
 [3] top-level scope at none:0

**Comment by odow** [comment]
We're making progress with this diagnostic thing. Is that path `/opt/gurobi810/linux64` correct?

**Comment by mao006006** [comment]
Yes, the path /opt/gurobi810/linux64 is correct. Thank you!

**Comment by odow** [comment]
Hmm, well it doesn't appear that it is, because we tried looking there and got the `unable to read directory` error.

What are the outputs of:
```Julia
@show readdir("/opt/gurobi810")
@show readdir("/opt/gurobi810/linux64")
@show readdir("/opt/gurobi810/linux64/lib")
```

**Comment by mao006006** [comment]
Hi Oscar,

I think I found a way to fix it. I set  
ENV["GUROBI_HOME"] = "/home/mao006006/opt/gurobi810/linux64/"

I don't know why honestly. I actually check my .bashrc file. It has 
export GUROBI_HOME="/opt/gurobi810/linux64"

But in Julia, I have to change it differently. Thank you so much for your help!!!

**Comment by odow** [comment]
Glad you got it sorted. Hopefully #222 should be more helpful in the future.
