### ISSUE TITLE
How to solve large sparse LP?

### ISSUE THREAD

**Issue by kwqswbb** [JuliaOpt/Gurobi.jl#224]
Hi,

I have a question about solving large sparse matrix LP problem. It really confused me for a long time.
If I have a form like this:
![image](https://user-images.githubusercontent.com/52946708/61265723-8664de80-a75f-11e9-87a5-19e96805da51.png)
I have all Fi data, which are in sparse form. So, how can I build a LP model to solve this problem faster? Could you please give me some clues? Thank you!

**Comment by kwqswbb** [comment]
For example, if I have tr(AiX)=bi, i=1,2,…,100. Ai is 1000*1000, Ai, X are symmetrix. How to build a LP model to solve this problem?

**Comment by odow** [comment]
Please add a link if you cross-post in other places: https://discourse.julialang.org/t/how-to-solve-large-sparse-lps-in-gurobi/26402

I'm going to close this issue since it isn't related to the Gurobi.jl wrapper, and we can continue the discussion on discourse.
