### ISSUE TITLE
julia> Pkg.add("LinearAlgebra") ERROR: unknown package LinearAlgebra

### ISSUE THREAD

**Issue by WANGrfy** [JuliaOpt/Gurobi.jl#228]
julia> Pkg.add("LinearAlgebra")
ERROR: unknown package LinearAlgebra

**Comment by blegat** [comment]
The LinearAlgebra package is part of the Julia standard library so you don't need to install it

**Comment by odow** [comment]
I'm closing this as un-related to Gurobi.jl. 

If you have other questions, feel free to post them on Discourse: https://discourse.julialang.org/c/domain/opt
