### ISSUE TITLE
Fix ObjectiveFunction in ListOfAttributesSet

### ISSUE THREAD

**Issue by odow** [JuliaOpt/Gurobi.jl#242]
This line should be the appropriate `ObjectiveFunction{T}` instead of just `ScalarAffineFunction`.

https://github.com/JuliaOpt/Gurobi.jl/blob/db91e1e9fabc3f62f30265780e6a577016ebba4e/src/MOI_wrapper.jl#L305

**Comment by blegat** [comment]
This error is present for almost every MOI wrapper.
The long term fix is to support only one objective function and to rely on https://github.com/JuliaOpt/MathOptInterface.jl/pull/789 to bridge the objective appropriately.
For QP solver that do something different when the objective is affine and not quadratic, the wrapper will still need to support two different objectives though.
