### ISSUE TITLE
Query Gurobi attributes from JuMP model

### ISSUE THREAD

**Issue by aahaselgrove** [JuliaOpt/Gurobi.jl#246]
I would like to query the optimality gap after my solver has completed execution. The Gurobi website indicates that this is an attribute of the solution (https://www.gurobi.com/documentation/6.5/refman/mipgap.html), but I can't see how to query this from a JuMP model (or, for that matter, from a Gurobi Model).

**Comment by odow** [comment]
General support is about to drop: https://github.com/JuliaOpt/Gurobi.jl/pull/247

But for now, 

```Julia
using JuMP, Gurobi
model = Model(with_optimizer(Gurobi.Optimizer))
# ...
optimize!(model)
MOI.get(model, MOI.RelativeGap())
```
The JuMP docs should be updated.
