### ISSUE TITLE
Duplicate variable names

### ISSUE THREAD

**Issue by mtanneau** [JuliaOpt/Gurobi.jl#249]
Giving the same name to two different variables does not raise an error (as per [MOI docs](http://www.juliaopt.org/MathOptInterface.jl/stable/apireference/#MathOptInterface.VariableName)).
However, doing so leads to an error being raised when looking up _any_ variable by name afterwards.

Is that a feature or a bug?

```julia
import Gurobi  # Gurobi master
import MathOptInterface  # MOI 0.9.2
MOI = MathOptInterface

m = Gurobi.Optimizer()
x = MOI.add_variable(m)
y = MOI.add_variable(m)
z = MOI.add_variable(m)

MOI.set(m, MOI.VariableName(), x, "x")
MOI.set(m, MOI.VariableName(), y, "x")  # duplicate name, does not raise an error
MOI.set(m, MOI.VariableName(), z, "z")

MOI.get(m, MOI.VariableIndex, "x")  # raises an error due to duplicate names
MOI.get(m, MOI.VariableIndex, "z")  # raises the same error. Should it?
```
Error message:
```julia
ERROR: Duplicate variable name detected: x
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] _rebuild_name_to_variable(::Gurobi.Optimizer) at /home/mathieu/GitHub/Gurobi.jl/src/MOI_wrapper.jl:471
 [3] get(::Gurobi.Optimizer, ::Type{MathOptInterface.VariableIndex}, ::String) at /home/mathieu/GitHub/Gurobi.jl/src/MOI_wrapper.jl:458
 [4] top-level scope at none:0
```

**Comment by odow** [comment]
It is probably arguable either way. It's probably not too hard to pass `name` into `_rebuild_name_to_variable` to only throw if it's the name being queried.
https://github.com/JuliaOpt/Gurobi.jl/blob/e328df70c05bd53175d36659cc81851786853084/src/MOI_wrapper.jl#L456-L476
Or to make `name_to_variable` store `nothing` if a duplicate name is detected and handle it differently.
