### ISSUE TITLE
My licence in Gurobi expired, I updated the licence, but it didn't help

### ISSUE THREAD

**Issue by NikitaBelyakAalto** [JuliaOpt/Gurobi.jl#254]
I have Gurobi v8.1.1.
I have a license that is valid, I have already checked it.
I am using JuMP (v.0.20.0) in Julia(v 1.2.0) model and with Gurobi solver. At some point, it started to indicate that the license is about to expire and I updated it. It didn't help and just now it just gives me the following message: 
![image](https://user-images.githubusercontent.com/53814737/65258417-87254280-db0b-11e9-8ce0-4244835176e9.png)
Moreover, when I am trying to use the command: 
![image](https://user-images.githubusercontent.com/53814737/65258490-a328e400-db0b-11e9-8ae5-3af2b56990d3.png)
which is weird since when I do
![image](https://user-images.githubusercontent.com/53814737/65258557-c5bafd00-db0b-11e9-9376-f53d0e71fcee.png)
It works. 
I have already changed ENV in the following way 
ENV["GUROBI_HOME"] = "/Library/gurobi811/mac64" and i can see the file "libgurobi81.dylib" there. However, when I try to use the command build it just responds false. 
Could you please tell me if there is any way to fix it?

**Comment by odow** [comment]
You can ignore the build command return `false`. 

Did you run `grbgetkey`? And save follow the instructions to save the license file in the right place, and/or set the appropriate environment variable? If so, you may just need to restart Julia (or Atom).

**Comment by NikitaBelyakAalto** [comment]
HI, thank you, I have double-checked the environment variable in Gurobi, and, apparently, it was not pointing to the correct location of the valid license file. Anyway, it works now. Thank you very much.

**Comment by odow** [comment]
Great!
