### ISSUE TITLE
Gurobi.GurobiError(10020, "Q matrix is not positive semi-definite (PSD)")

### ISSUE THREAD

**Issue by ArielxX** [JuliaOpt/Gurobi.jl#255]
Hi, I'm trying to solve a class of optimization problems with quadratic objective function but also with some quadratic constraints with the form `r(x) * s(x) <= t`where `r` and `s` are lineal function and `t` is a constant.

For this problems I want to use the Gurobi solver in julia.

My julia verision is 1.2.0 and I'm using Gurobi 8.11.

Everything works perfectly when the constraints are lineal, but with quadratic constraint it doesn't. For example in this particular easy problem:

```
min: ( (x1-1)^2 + (x2-2)^2 + (x3-1)^2 ) / 2
 
s.t.:
x1, x2, x3 >= 0
x1 * x3 <= 1
x2 * x3 <= 1
```

it said this error:

`Gurobi.GurobiError(10020, "Q matrix is not positive semi-definite (PSD)")`

What does that mean exactly? What's this Q matrix? I think that is the matrix of the application of each quadratic constraint, because if I change those constraint to:

```
x1^2 <= t
x3^2 <= t
```

it works 

Can you help me? There isn't any way to solve my original problem using Gurobi?

I will appreciate every help, thanks

**Comment by odow** [comment]
> What's this Q matrix? I think that is the matrix of the application of each quadratic constraint

Correct. 

Gurobi only supports convex quadratic problems. `x1 * x3` is a bilinear, non-convex term, and so, looking at the Q matrix from x'Q x <= 1, the Q matrix is not PSD. 

There is no way to solve your original problem using Gurobi. You could try Ipopt instead (`] Ipopt`, `using Ipopt`, `Ipopt.Optimizer`), but note that you will only find a locally optimal solution.

**Comment by ArielxX** [comment]
Ok, thank you very much for your answer. And that was what I thought. I'm using Ipopt already, but as you said I'm just obtaining a locally optimal solution. For this particular problem is veeery near to the real solution but the idea is to solve harder problems.

So, my question is, do you know about another solver in julia to use for this kind of problems, maybe CPLEX, I don't really know if this one works.

Thank you

**Comment by tkoolen** [comment]
You could use a mixed-integer nonlinear program silver like SCIP (wrapper: https://github.com/SCIP-Interfaces/SCIP.jl), which should be able to give you a global minimizer as long as you specify upper bounds on the decision variables as well. I think Gurobi is adding support for nonconvex quadratics in the upcoming version as well.

**Comment by ArielxX** [comment]
> You could use a mixed-integer nonlinear program silver like SCIP (wrapper: https://github.com/SCIP-Interfaces/SCIP.jl), which should be able to give you a global minimizer as long as you specify upper bounds on the decision variables as well. I think Gurobi is adding support for nonconvex quadratics in the upcoming version as well.

Ok, I'll follow your advise
And let's hope Gurobi don't take too long doing that.

Thank you very much

**Comment by odow** [comment]
I'll close this since it appears to be resolved and isn't an issue with the Gurobi wrapper.
