### ISSUE TITLE
ERROR: Failed to create environment (error 10023)

### ISSUE THREAD

**Issue by stumarcus576** [JuliaOpt/Gurobi.jl#260]
I use Julia v0.6.4 and JuMP v0.18. I did a Pkg.update("Gurobi.jl"). My Gurobi v7.5 license file works, but when I attempt to use the Gurobi v8.1 license file, I get the following error in the REPL.

julia> using JuMP, Gurobi

julia> const GRB_ENV = Gurobi.Env()
ERROR: Failed to create environment (error 10023).
Stacktrace:
 [1] Gurobi.Env() at /Users/a598124/.julia/v0.6/Gurobi/src/grb_env.jl:15

The Gurobi 10023 error means JOB_REJECTED: https://www.gurobi.com/documentation/8.1/refman/error_codes.html

Gurobi Compute Server responded, but was unable to process the job (typically because the queuing time exceeded the user-specified timeout or because the queue has exceeded its maximum capacity)

I am able to use Gurobi v8.1 through a simple test MIP Python script with the Gurobi v8.1 license file.

**Comment by odow** [comment]
You should contact Gurobi for support. This is just calling the `loadenv` C function, so it's not Julia-specific (unless we need to set some options somewhere): 
https://github.com/JuliaOpt/Gurobi.jl/blob/4bc1f91a398fd149c3c0c0fdb4288a5b08b46957/src/grb_env.jl#L4-L22

**Comment by stumarcus576** [comment]
I resolved the problem by the following steps: 0) conda install gurobi=8.1.1 1) added export GUROBI_HOME="/Users/a598124/anaconda2" to my .bash_profile file in my home directory on macOS, 2) did Pkg.build("Gurobi") in the Julia REPL, 3) quit the Julia REPL, 4) restarted the Julia REPL, and 5) Gurobi v8.1 works now.
