### ISSUE TITLE
Reading Data from Infeasible QP Models

### ISSUE THREAD

**Issue by ccoffrin** [JuliaOpt/Gurobi.jl#274]
Given the following model,
```julia
using JuMP
using Gurobi

m = Model()

@variable(m, x >= 0.0000001)

#@objective(m, Min, x) # works fine
@objective(m, Min, x^2) # breaks

@constraint(m, x <= -0.000001)

optimize!(m, with_optimizer(Gurobi.Optimizer, Method=2))

value(x)
```
When the objective is linear everything works fine.  If the objective is quadratic I get the following error,
```
ERROR: LoadError: Gurobi.GurobiError(10005, "Unable to retrieve attribute 'X'")
Stacktrace:
 [1] get_dblattrelement(::Gurobi.Model, ::String, ::Int64) at ~/.julia/packages/Gurobi/TX8tY/src/grb_attrs.jl:68
 [2] get(::Gurobi.Optimizer, ::MathOptInterface.VariablePrimal, ::MathOptInterface.VariableIndex) at ~/.julia/packages/Gurobi/TX8tY/src/MOI_wrapper.jl:1856
```

Tested with Julia v1.2, Gurobi.jl v0.7.3, Gurobi v8.1

**Comment by odow** [comment]
You should use [`has_values(model)`](https://www.juliaopt.org/JuMP.jl/v0.20.0/solutions/#JuMP.has_values) before querying `value`.

What do you expect `value(x)` to return if the model is infeasible?

**Comment by ccoffrin** [comment]
I agree the behavior of Gurobi is quite odd, but this raises a broader point about consistent behavior across solvers.  Since its inception, PowerModels has assumed that `value(x)` will always return some value, even if that value is junk (e.g. `NaN`, initial value, random internal state).  By design or not, that invariant has been true in all cases thus far until this specific case.  So if the proper design is to check `has_values` first, probably some cross MOI test should be added?

**Comment by mlubin** [comment]
> Since its inception, PowerModels has assumed that value(x) will always return some value, even if that value is junk (e.g. NaN, initial value, random internal state). By design or not, that invariant has been true in all cases thus far until this specific case.

This is not the design of MOI. http://www.juliaopt.org/JuMP.jl/dev/solutions/#Obtaining-solutions-1 says:

> It is important to note that if has_values or has_duals return false, calls to value and dual might throw an error or return arbitrary values.

It's not obvious how to add test coverage for "throw an error or return arbitrary values".

**Comment by ccoffrin** [comment]
Sure, so how can I test that my code works under the `has_values(m) == false` condition?  Some kind of a mock solver?

**Comment by odow** [comment]
The infeasible linear case you have above will have `has_values(m) == false`.

**Comment by mlubin** [comment]
You could use [MockOptimizer](https://github.com/JuliaOpt/MathOptInterface.jl/blob/master/src/Utilities/mockoptimizer.jl). See JuMP's tests for examples.

**Comment by ccoffrin** [comment]
Ok, I get it.  

Going back to Miles question about cross-solver tests.  One test that could be considered is that if `has_values(m) == false` then calls to `value(x)` could raise an exception (and the same with duals).  The LP case in the above code provides an example where no values are present, but calls to `value(x)` work, which seems inconsistent with the `has_values` semantics.

**Comment by odow** [comment]
> The LP case in the above code provides an example where no values are present, but calls to value(x) work, which seems inconsistent with the has_values semantics.

It follow the documentation, returning an arbitrary value.

> "It is important to note that if has_values or has_duals return false, calls to value and dual might throw an error or return arbitrary values."

This decision was made to avoid solvers having to wrap every query in a try-catch, or having to store a `has_values` flag and check that flag on every query.

PowerModels could define
```Julia
function PowerModels.value(x::JuMP.VariableRef)
    return JuMP.has_values(JuMP.owner_model(x)) ? JuMP.value(x) : NaN
end
```

**Comment by ccoffrin** [comment]
I think we can close this issue as this is clarified as a bug in my use of JuMP.  If there is still interest in discussion we could move this point to a JuMP.jl issue. 

@odow, for example you could consider adding the guarded `value` function you propose into JuMP, so that the default JuMP behavior is robust for novice users, and have something like `JuMP.value_internal(x)` for advanced users who want performance over reliability.
