### ISSUE TITLE
NonConvex Parameter

### ISSUE THREAD

**Issue by chenandtonic** [JuliaOpt/Gurobi.jl#280]
Hello,

I would like to change the NonConvex parameter, but access does not seem available via Julia. I am getting the error:
Unrecognized parameter name: NonConvex.

This is with Gurobi.jl v0.7.4 and Gurobi 9.0.  I can set the parameter, for instance, in MATLAB.

Thanks!

**Comment by odow** [comment]
It needs to be added to the correct vector in
https://github.com/JuliaOpt/Gurobi.jl/blob/master/src/grb_params.jl

I don't have a copy of Gurobi 9 so can't test etc.

**Comment by mao006006** [comment]
> It needs to be added to the correct vector in
> https://github.com/JuliaOpt/Gurobi.jl/blob/master/src/grb_params.jl
> 
> I don't have a copy of Gurobi 9 so can't test etc.

I check and confirm that adding ``NonConvex'' to the list works.

**Comment by chenandtonic** [comment]
Yup that fixed it thanks!

**Comment by zoe667** [comment]
Hi, the link https://github.com/JuliaOpt/Gurobi.jl/blob/master/src/grb_params.jl seems not work now, can anyone help me redirect to the page so that I can check how to set NonConvex parameter? Thanks in advance

**Comment by odow** [comment]
Hi @zoe667,

Here's how you can set the parameter:
```julia
model = Model(Gurobi.Optimizer)
set_attribute(model, "NonConvex", 2)
``` 

(That page doesn't link because it's old and out-of-date now.)
