### ISSUE TITLE
Invalid Gurobi license in Juno only

### ISSUE THREAD

**Issue by YoungFaithful** [JuliaOpt/Gurobi.jl#287]
I use:
- `julia@1.3.1` (also tested with `julia@1.1.0`)
- `gurobi901`
- `Gurobi.jl@0.7.5`
- `Atom@0.11.3`
- `Juno@ 0.7.2`
I recieve the `ERROR: Invalid Gurobi license` using Juno. Using the terminal works fine.
It didn't help to change the different julia boot options (basic, cycler, or external terminal).
![image](https://user-images.githubusercontent.com/10561245/74016349-8e51cd80-4992-11ea-8983-f45c6341b27a.png)
![image](https://user-images.githubusercontent.com/10561245/74018377-1c7b8300-4996-11ea-9425-adaa50126e6f.png)
Thanks for your support.

**Comment by odow** [comment]
Weird. What if you run `Pkg.build("Gurobi")` in Juno? What's the output of `ENV["GUROBI_HOME"]`?

**Comment by YoungFaithful** [comment]
I found that the ENV variables differ between Juno and a normal Terminal:
In the terminal the variables defined in `~/.bashrc` are included.
In Juno those are not included.
