### ISSUE TITLE
Could not load library "gurobi81"

### ISSUE THREAD

**Issue by biswajit216** [JuliaOpt/Gurobi.jl#289]
Hi,
I installed Gurobi optimizer version 9.0.1 to use along with Julia. But when I try to use the package I get an error saying 
**LoadError: error compiling #GurobiMathProgModel#18: could not load library "gurobi81"
The specified module could not be found.**
Can anyone please help me to resolve this?
Thanks.

**Comment by odow** [comment]
If you've installed Gurobi 9.0 recently, you probably need to close Julia, open a new session, then run:
```Julia
import Pkg
Pkg.build("Gurobi")
using Gurobi
```

**Comment by biswajit216** [comment]
> If you've installed Gurobi 9.0 recently, you probably need to close Julia, open a new session, then run:
> 
> ```julia
> import Pkg
> Pkg.build("Gurobi")
> using Gurobi
> ```

It worked. Thank you so much!
