### ISSUE TITLE
MethodError: no method matching Gurobi.Env(::Ptr{Nothing})

### ISSUE THREAD

**Issue by KenZhenLin** [JuliaOpt/Gurobi.jl#290]
Hello,
I tried setting the Gurobi parameter "NonConvex" to 2 and I got the following error: "MethodError: no method matching Gurobi.Env(::Ptr{Nothing})". My Julia Gurobi version is v0.7.5 and I am using Julia 1.3.1. I got this error with JuMP v0.18.6 and v0.20.1. I would appreciate it if you could help me! Please see the screenshot below:

JuMP v0.18.6:
<img width="591" alt="gurobi_error" src="https://user-images.githubusercontent.com/56413662/74400099-fe28e380-4dea-11ea-8a3b-5fef35d0ad36.png">

JuMP v0.20.1:
<img width="646" alt="gurobi_error2" src="https://user-images.githubusercontent.com/56413662/74400149-1993ee80-4deb-11ea-8a47-ecdb4eb03a0b.png">

**Comment by blegat** [comment]
Please reference when you [double post](https://discourse.julialang.org/t/methoderror-no-method-matching-gurobi-env-ptr-nothing/34555).
MRE:
```julia
julia> using Gurobi

julia> model = Gurobi.Model(Gurobi.Env(), "")
Academic license - for non-commercial use only
Gurobi Model: 
    type   : LP
    sense  : minimize
    number of variables             = 0
    number of linear constraints    = 0
    number of quadratic constraints = 0
    number of sos constraints       = 0
    number of non-zero coeffs       = 0
    number of non-zero qp objective terms  = 0
    number of non-zero qp constraint terms = 0


julia> Gurobi.set_str_param!(model, "Foobar", "")
ERROR: MethodError: no method matching Gurobi.Env(::Ptr{Nothing})
Closest candidates are:
  Gurobi.Env() at /home/blegat/.julia/packages/Gurobi/CI8ht/src/grb_env.jl:8
Stacktrace:
 [1] set_str_param!(::Gurobi.Model, ::String, ::String) at /home/blegat/.julia/packages/Gurobi/CI8ht/src/grb_params.jl:300
 [2] top-level scope at REPL[3]:1

julia> Gurobi.set_int_param!(model, "Foobar", 0)
ERROR: MethodError: no method matching Gurobi.Env(::Ptr{Nothing})
Closest candidates are:
  Gurobi.Env() at /home/blegat/.julia/packages/Gurobi/CI8ht/src/grb_env.jl:8
Stacktrace:
 [1] set_int_param!(::Gurobi.Model, ::String, ::Int64) at /home/blegat/.julia/packages/Gurobi/CI8ht/src/grb_params.jl:275
 [2] top-level scope at REPL[4]:1
```
