### ISSUE TITLE
Write to Excel-file

### ISSUE THREAD

**Issue by Christl96** [JuliaOpt/Gurobi.jl#296]
How can I write the solutions of my optimization model in a Excel-file?
I tried to use the write_to_file function:
```
write_to_file(
    model::Model,
    filename::String;
    format::MOI.FileFormats.FileFormat = MOI.FileFormats.FORMAT_AUTOMATIC
)
```
I used it as
`JuMP.write_to_file(model, "filename", .csv) `
and 
`write_to_file(model,` "filename", .csv) `
but it is not working for me

**Comment by odow** [comment]
Hi there. `write_to_file` is for writing the model, not the solution.

You could do something like
```Julia
function write_to_csv(model::Model, filename::String)
    open(filename, "w") do io
        for x in all_variables(model)
            println(io, name(x), ", ", value(x))
        end
    end
end
write_to_csv(model, "/tmp/model.csv")
```

p.s. Questions like this are better posted on https://discourse.julialang.org/c/domain/opt/13. That way others can find this solution if they have similar issues.

**Comment by odow** [comment]
Closing because this is not an issue with the Gurobi.jl wrapper. Please post on Discourse if you have similar questions in future :)
