### ISSUE TITLE
I want to use Gurobi in julia (in window power shell)

### ISSUE THREAD

**Issue by realcircle** [JuliaOpt/Gurobi.jl#297]
```Julia
julia> using JuMP
[ Info: Precompiling JuMP [4076af6c-e467-56ae-b986-b466b2749572]

julia> using Pkg

julia> Pkg.add("Gurobi")
  Updating registry at `C:\Users\name\.julia\registries\General`
┌ Warning: Some registries failed to update:
│     — `C:\Users\name\.julia\registries\General` — registry dirty
└ @ Pkg.Types D:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.3\Pkg\src\Types.jl:1199
 Resolving package versions...
  Updating `C:\Users\name\.julia\environments\v1.3\Project.toml`
 [no changes]
  Updating `C:\Users\name\.julia\environments\v1.3\Manifest.toml`
 [no changes]

julia> using Gurobi
[ Info: Precompiling Gurobi [2e9cd046-0924-5485-92f1-d5272153d98b]
ERROR: LoadError:     Gurobi not properly installed. Please run Pkg.build("Gurobi"). For
    more information go to https://github.com/JuliaOpt/Gurobi.jl

Stacktrace:
 [1] top-level scope at C:\Users\name\.julia\packages\Gurobi\CI8ht\src\Gurobi.jl:7
 [2] top-level scope at none:2
in expression starting at C:\Users\name\.julia\packages\Gurobi\CI8ht\src\Gurobi.jl:4
ERROR: Failed to precompile Gurobi [2e9cd046-0924-5485-92f1-d5272153d98b] to C:\Users\name\.julia\compiled\v1.3\Gurobi\do9v6_HJEuV.ji.
Stacktrace:
 [1] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [2] _require(::Base.PkgId) at .\loading.jl:1024
 [3] require(::Base.PkgId) at .\loading.jl:922
 [4] require(::Module, ::Symbol) at .\loading.jl:917

julia> Pkg.build("Gurobi")
  Building CodecBzip2 → `C:\Users\name\.julia\packages\CodecBzip2\T5yr7\deps\build.log`
  Building CodecZlib ─→ `C:\Users\name\.julia\packages\CodecZlib\5t9zO\deps\build.log`
  Building Gurobi ────→ `C:\Users\name\.julia\packages\Gurobi\CI8ht\deps\build.log`
┌ Error: Error building `Gurobi`:
│ ERROR: LoadError: Unable to locate Gurobi installation. If the advice above did not help,
│ open an issue at https://github.com/JuliaOpt/Gurobi.jl and post the full
│ print-out of this diagnostic attempt.
│
│ Stacktrace:
│  [1] top-level scope at C:\Users\name\.julia\packages\Gurobi\CI8ht\deps\build.jl:154
│  [2] top-level scope at none:5
│ in expression starting at C:\Users\name\.julia\packages\Gurobi\CI8ht\deps\build.jl:152
│ Unable to locate Gurobi installation. Running some common diagnostics.
│
│ Gurobi.jl only supports the following versions:
│
│  - gurobi90
│  - gurobi81
│  - gurobi80
│  - gurobi75
│  - gurobi70
│
│ Did you download and install one of these versions from gurobi.com?
│
│
│ Found GUROBI_HOME =  C:\gurobi901\win64\gurobi.lic
│
│ Does this point to the correct install location?
│ - on Windows, this might be `C:\Program Files\gurobi810\win64\`
│ - alternatively, on Windows, this might be `C:/Program Files/gurobi810/win64/`
│ - on OSX, this might be `/Library/gurobi810/mac64/`
│ - on Unix, this might be `/home/my_user/gurobi810/linux64/`
│
│ Note: this has to be a full path, not a path relative to your current
│ directory or your home directory.
│
│ We're going to look for the Gurobi library in this directory:
│     C:\gurobi901\win64\gurobi.lic\bin
│
│ That directory has the following files:
│
│ Aha! We tried looking in `C:\gurobi901\win64\gurobi.lic\bin`, but something went wrong. Are
│ you sure that your GUROBI_HOME environment variable is correct?
│ When combined with the appropriate suffix (e.g., `lib` or
│ `bin`, it needs to point to a valid directory.
└ @ Pkg.Operations D:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.3\Pkg\src\backwards_compatible_isolation.jl:649
false
```
------------------------------------------------------------------------------------------------------
I want to use Gurobi in julia (in window power shell)
but I can't solve this problem....

**Comment by realcircle** [comment]
license: Academic License

**Comment by odow** [comment]
As stated in the error message, your `GUROBI_HOME` environment variable is not correct. It should just be `C:/gurobi901/win64`.

```Julia
ENV["GUROBI_HOME"] = "C:/gurobi901/win64"
import Pkg
Pkg.build("Gurobi")
```

In addition, the location of your license file needs to be in the environment variable `GRB_LICENSE_FILE`.

**Comment by realcircle** [comment]
julia> ENV["GUROBI_HOME"] = "C:/gurobi901/win64"
"C:/gurobi901/win64"

julia> import Pkg

julia> Pkg.build("Gurobi")
  Building CodecBzip2 → `C:\Users\진원\.julia\packages\CodecBzip2\T5yr7\deps\build.log`
  Building CodecZlib ─→ `C:\Users\진원\.julia\packages\CodecZlib\5t9zO\deps\build.log`
  Building Gurobi ────→ `C:\Users\진원\.julia\packages\Gurobi\CI8ht\deps\build.log`
┌ Error: Error building `Gurobi`:
│ ERROR: LoadError: Unable to locate Gurobi installation. If the advice above did not help,
│ open an issue at https://github.com/JuliaOpt/Gurobi.jl and post the full
│ print-out of this diagnostic attempt.
│
│ Stacktrace:
│  [1] top-level scope at C:\Users\진원\.julia\packages\Gurobi\CI8ht\deps\build.jl:154
│  [2] top-level scope at none:5
│ in expression starting at C:\Users\진원\.julia\packages\Gurobi\CI8ht\deps\build.jl:152
│ Unable to locate Gurobi installation. Running some common diagnostics.
│
│ Gurobi.jl only supports the following versions:
│
│  - gurobi90
│  - gurobi81
│  - gurobi80
│  - gurobi75
│  - gurobi70
│
│ Did you download and install one of these versions from gurobi.com?
│
│
│ Found GUROBI_HOME =  C:/gurobi901/win64
│
│ Does this point to the correct install location?
│ - on Windows, this might be `C:\Program Files\gurobi810\win64\`
│ - alternatively, on Windows, this might be `C:/Program Files/gurobi810/win64/`
│ - on OSX, this might be `/Library/gurobi810/mac64/`
│ - on Unix, this might be `/home/my_user/gurobi810/linux64/`
│
│ Note: this has to be a full path, not a path relative to your current
│ directory or your home directory.
│
│ We're going to look for the Gurobi library in this directory:
│     C:/gurobi901/win64/bin
│
│ That directory has the following files:
│
│  - C:/gurobi901/win64/bin/grbcluster.exe
│  - C:/gurobi901/win64/bin/grbgetkey.exe
│  - C:/gurobi901/win64/bin/grbprobe.exe
│  - C:/gurobi901/win64/bin/grbtune.exe
│  - C:/gurobi901/win64/bin/grbtune.log
│  - C:/gurobi901/win64/bin/grb_ts.exe
│  - C:/gurobi901/win64/bin/gurobi.bat
│  - C:/gurobi901/win64/bin/gurobi.env
│  - C:/gurobi901/win64/bin/gurobi.log
│  - C:/gurobi901/win64/bin/gurobi90.dll
│  - C:/gurobi901/win64/bin/Gurobi90.NET.dll
│  - C:/gurobi901/win64/bin/Gurobi90.NET.XML
│  - C:/gurobi901/win64/bin/gurobi90_light.dll
│  - C:/gurobi901/win64/bin/GurobiJni90.dll
│  - C:/gurobi901/win64/bin/gurobi_cl.exe
│  - C:/gurobi901/win64/bin/pysetup.bat
│  - C:/gurobi901/win64/bin/vslauncher.exe
│  - C:/gurobi901/win64/bin/vswhere.exe
│
│ We were looking for (but could not find) a file named like
│ `libgurobiXXX.so`, `libgurobiXXX.dylib`, or `gurobiXXX.dll`. You
│ should update your GUROBI_HOME environment variable to point to the
│ correct location.
└ @ Pkg.Operations D:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.3\Pkg\src\backwards_compatible_isolation.jl:649
false
-------------------------------------------------------------------
And  I added license file in the environment variable 
but have same result....

**Comment by odow** [comment]
Very weird! It looks like it should work...

What is the output of:
```Julia
import Libdl
path = joinpath(ENV["GUROBI_HOME"], "bin", string("gurobi90", ".", Libdl.dlext))
@show path
@show Libdl.dlopen_e(path)
```

Do you have permission to open files in `C:/gurobi901`?

**Comment by odow** [comment]
Any update? If not, I will close as stale.

**Comment by odow** [comment]
Closing as stale. Please re-open if you still have issues.
