### ISSUE TITLE
Unknown parameter: 'NonConvex' 

### ISSUE THREAD

**Issue by Hrj9499** [JuliaOpt/Gurobi.jl#305]
Hi there. I encounter a problem similar to what was reported in the last issue. I updated my Gurobi package to version 0.7.6 (and I also tried 0.7.5) but still get this information. Here is a screenshot of my package status. Thanks for any help! 
![JuliaPackageVersion](https://user-images.githubusercontent.com/40732276/78422819-cf194a80-7694-11ea-9d11-151064c0293a.png)

**Comment by odow** [comment]
Please provide a minimal reproducible example. Are you using Gurobi 9.0?

**Comment by odow** [comment]
Any update? If not, I will close as stale.

**Comment by odow** [comment]
Closing as stale. Please re-open if you still have issues.
