### ISSUE TITLE
Need to manually set GUROBI_HOME on Mac

### ISSUE THREAD

**Issue by EdvinAblad** [JuliaOpt/Gurobi.jl#318]
Many of my students who use Mac have the same issue.

When they add/build Gurobi it complains about GUROBI_HOME.
The issue is resolved by adding 
`export GUROBI_HOME="/Library/gurobi901/mac64"`
to the .bash_profile

Can this step be skipped?

(Sadly I don't have a Mac myself so I cannot replicate the issue)

**Comment by odow** [comment]
How did they install Gurobi? I think this environment variable should get set automatically.

They can also do this in Julia when installing Gurobi
```Julia
ENV["GUROBI_HOME"] = "/Library/gurobi901/mac64"
import Pkg
Pkg.add("Gurobi")
```

**Comment by EdvinAblad** [comment]
Ahh sorry, then maybe it is an issue of the Mac gurobi installer (hard to try since I dont use Mac myself).
However, they all told me they used the latest Mac64 version from: https://www.gurobi.com/downloads/gurobi-software/

**Comment by odow** [comment]
There are instructions in the readme for what to do when they get this error: https://github.com/JuliaOpt/Gurobi.jl#loaderror-unable-to-locate-gurobi-installation
