### ISSUE TITLE
Failed to install Gurobi to Julia

### ISSUE THREAD

**Issue by MirelEce** [JuliaOpt/Gurobi.jl#324]
Hi!

I am new to Julia and Gurobi. I am using Windows x64 and just downloaded julia v0.6.4 (I am advised to install this version than the newer versions) and Gurobi 9.0.2.  Gurobi is installed, license is activated and seems fine. 

I did not have any problems when I installed JuMP package, but could not install Gurobi to Julia afterwards.  There is no file called "deps.jl" in the directory C:\Users\mirel\.julia\v0.6\Gurobi\deps  ; just .gitignore and build.jl.  

When I try Pkg.build("Gurobi") , I get the following error:

LoadError: Unable to locate Gurobi installation. Note that this must be downloaded separately from gurobi.com
while loading C:\Users\mirel\.julia\v0.6\Gurobi\deps\build.jl, in expression starting on line 62

========================================================================================================================

====================================================[ BUILD ERRORS ]====================================================

WARNING: Gurobi had build errors.

 - packages with build errors remain installed in C:\Users\mirel\.julia\v0.6
 - build the package(s) and all dependencies with `Pkg.build("Gurobi")`
 - build a single package by running its `deps/build.jl` script

========================================================================================================================

I checked some relevant previous issues and their responses. My environment is correctly set, i.e.,
ENV["GUROBI_HOME"]
"C:\\gurobi902\\win64".

Also, for the reading directories:

@show readdir("C:\\gurobi902\\win64")
readdir("C:\\gurobi902\\win64") = String["bin", "docs", "EULA.doc", "EULA.pdf", "examples", "include", "lib", "matlab", "python27", "python35", "python36", "python37", "python38", "R", "ReleaseNotes.html", "setup.py", "src"]
17-element Array{String,1}:
 "bin"
 "docs"
 "EULA.doc"
 "EULA.pdf"
 "examples"
 "include"
 "lib"
 "matlab"
 "python27"
 "python35"
 "python36"
 "python37"
 "python38"
 "R"
 "ReleaseNotes.html"
 "setup.py"
 "src"

julia> @show readdir("C:\\gurobi902\\win64\bin")
ERROR: SystemError: unable to read directory C:\gurobi902\win6in: Unknown error
Stacktrace:
 [1] readdir(::String) at .\file.jl:415

Could you please help me fix this issue, I truly appreciate it!!

**Comment by odow** [comment]
Please upgrade to Julia 1.0. Julia 0.6.4 has been unsupported for almost two years.

**Comment by MirelEce** [comment]
Is the issue I am having related to the version being unsupported and would resolve if I upgrade? 
I downloaded the older version as it was suggested by my instructor because "some codes are changed in the newer versions and I would not be able to execute the files unless I modify them".

**Comment by odow** [comment]
Try installing Gurobi 8.1. Gurobi 9.0 won't work. (The error message in the latest version is much improved to help people diagnose these sorts of issues.)
 https://github.com/JuliaOpt/Gurobi.jl/blob/ee3d837ea3c375b5dc2cca4dac61f6dd0a7541aa/deps/build.jl#L26

**Comment by MirelEce** [comment]
Thank you so much for your responses, issue is resolved when I installed Gurobi 8.1.1.

**Comment by odow** [comment]
No worries. I _strongly_ encourage you to upgrade the code as soon as possible. Code written for Julia 1.0 will continue to run on all future 1.X releases. Julia has finally achieved some stability which is good news for projects such as this. It also has a `Manifest.toml` system which makes reproducing the package versions you need seamless.
