### ISSUE TITLE
Gurobi not installing correctly on OSX

### ISSUE THREAD

**Issue by rgiordan** [JuliaOpt/Gurobi.jl#33]
Hi Gurobi,

I'm new to Julia and trying to install Gurobi.jl.  I can add it and Pkg.build("Gurobi") completes successfully, but when I try to use it, it tells me to run Pkg.build again.

    julia> Pkg.add("Gurobi")
    INFO: Installing Gurobi v0.1.25
    INFO: Building Gurobi
    INFO: Package database updated
    
    julia> Pkg.build("Gurobi")
    INFO: Building Gurobi

    julia> using Gurobi
    ERROR: Gurobi not properly installed. Please run Pkg.build("Gurobi")
     in error at error.jl:21
     in include at /Applications/Julia-0.3.6.app/Contents/Resources/julia/lib/julia/sys.dylib
     in include_from_node1 at /Applications/Julia-0.3.6.app/Contents/Resources/julia/lib/julia/sys.dylib
     in reload_path at loading.jl:152
     in _require at loading.jl:67
     in require at loading.jl:51
    while loading /Users/ryangiordanonon-admin/.julia/v0.3/Gurobi/src/Gurobi.jl, in expression starting on line 6
    
    julia> Pkg.build("Gurobi")
    INFO: Building Gurobi

    julia> 

Pkg.test("Gurobi") also fails:

    julia> Pkg.test("Gurobi")
    INFO: Testing Gurobi
    running lp_01a.jl ...
    ERROR: Gurobi not properly installed. Please run Pkg.build("Gurobi")
     in error at error.jl:21
     in include at /Applications/Julia-0.3.6.app/Contents/Resources/julia/lib/julia/sys.dylib

Thanks in advance for your help,
Ryan

**Comment by IainNZ** [comment]
Hi @rgiordan, just so you know, this package is maintained by volunteers, not the Gurobi company.

Anyway, do you have a Gurobi license?

**Comment by rgiordan** [comment]
Ah, I didn't realize that I needed a license.  Sorry to bother you, I will use a different package.

**Comment by IainNZ** [comment]
If you are an academic/student, they do have free licenses. Otherwise you probably want to try Cbc
