### ISSUE TITLE
Error building `Gurobi` with Julia

### ISSUE THREAD

**Issue by ElizaFrench** [JuliaOpt/Gurobi.jl#332]
![Screen Shot 2020-06-01 at 12 31 17 PM](https://user-images.githubusercontent.com/55071581/83430508-cbd7dc00-a403-11ea-9eb9-779b31c27aca.png)

**Comment by odow** [comment]
As per the error message, your environment variable should just be `Library/gurobi902/mac64/`.

**Comment by ElizaFrench** [comment]
> As per the error message, your environment variable should just be `Library/gurobi902/mac64/`.

But when I do type in the command window:
ENV["GUROBI_HOME"] = "Library/gurobi902/mac64"
and then try to run import Pkg; Pkg.build("Gurobi")
I keep getting the error

**Comment by odow** [comment]
I guess I meant `/Library/gurobi902/mac64/`. Note the first forward-slash.

**Comment by ElizaFrench** [comment]
Ah thank you that seemed to help

**Comment by odow** [comment]
Great
