### ISSUE TITLE
Bug in GurobiSolverInterface.jl/getconstrsolution

### ISSUE THREAD

**Issue by adelarue** [JuliaOpt/Gurobi.jl#40]
I've been using your wonderful Gurobi wrapper with JuMP and MathProgBase for a few months now and it's been an absolute joy, and today I think I found a small bug in getconstrsolution. When a constraint is not tight, getconstrsolution returns a value that is not within constraint bounds.
For instance, the first half of the following code fails, while the second does not:
```julia
# getconstrsolutionTest.jl

using JuMP, MathProgBase, Gurobi

# Slack GEQ constraint
m = Model(solver=GurobiSolver())
@defVar(m, x)
@addConstraint(m, x >= 0)
@addConstraint(m, x >= 3)
@setObjective(m, Min, x)

buildInternalModel(m)
im = getInternalModel(m)

MathProgBase.optimize!(im)

for i = 1:length(MathProgBase.getconstrLB(im))
	println("Checking constraint $i")
	@assert MathProgBase.getconstrLB(im)[i] <= MathProgBase.getconstrsolution(im)[i] <= MathProgBase.getconstrUB(im)[i]
end

# Slack LEQ constraint
m = Model(solver=GurobiSolver())
@defVar(m, x)
@addConstraint(m, x <= 3)
@addConstraint(m, x <= 0)
@setObjective(m, Max, x)

buildInternalModel(m)
im = getInternalModel(m)

MathProgBase.optimize!(im)

for i = 1:length(MathProgBase.getconstrLB(im))
	println("Checking constraint $i")
	@assert MathProgBase.getconstrLB(im)[i] <= MathProgBase.getconstrsolution(im)[i] <= MathProgBase.getconstrUB(im)[i]
end
```
I think this is because the variables that represent slackness of a constraint might have an overall sign, which leads to a sign error on line 264 of GurobiSolverInterface.jl. Is this correct ?

Thanks for your help !

**Comment by mlubin** [comment]
This could be an issue. If you can find a bug in the logic [here](https://github.com/JuliaOpt/Gurobi.jl/blob/master/src/GurobiSolverInterface.jl#L250), PRs are accepted :)
It would be good to add this as a test to [MathProgBase](https://github.com/JuliaOpt/MathProgBase.jl/blob/0132f42277c90a866238bf18ebf8641a9b5d7466/test/linproginterface.jl) as well.

**Comment by adelarue** [comment]
Unfortunately I'm rather new to Git and I don't know how to do a pull request. I've also never interacted with Gurobi's API before, but I can try to take a careful look at it sometime next week.

**Comment by mlubin** [comment]
Happy to help out with the PR. If it's a small change, you can do it without going through the command line, just browse to the file on github and click the "edit this file" icon next to Raw/Blame/History buttons on the top right.

**Comment by odow** [comment]
@mlubin Can this be closed now?

**Comment by mlubin** [comment]
Suppose so, but we never got a test.

**Comment by odow** [comment]
I'll add it when I get time. https://github.com/JuliaOpt/MathProgBase.jl/issues/122
