### ISSUE TITLE
Support in addvars! for SparseMatrixCSC

### ISSUE THREAD

**Issue by klkeys** [JuliaOpt/Gurobi.jl#50]
I am trying to use the Gurobi.jl interface to solve an LP (`min c'x s.t. Ax == b`) with parameters `c`, `A`, and `b` all of type `SparseMatrixCSC{Float64,Int64}`. I simulate them as follows:

    m = 5000    # nrows
    n = 10000  # ncols
    s = 0.01    # sparsity level
    A = sprandn(m,n,s)
    c = sprand(m,1,s)
    y = sprandn(n,1,s)
    x = sparsevec(y.rowval,max(y.nzval,0.0),y.m)
    b = A*x + sprand(m,1,s)

I match the Gurobi variable names: `f == c`, `Aeq == A`, and `beq == b`.

`addvars!` throws an error if I feed it a sparse vector `f`. Does the Gurobi solver not admit sparse parameters for solving big LPs?

Note that I may not be simulating my LP parameters intelligently; having a sparse `f` may not make sense in the real world (and if it is not, please correct me!)

**Comment by mlubin** [comment]
Gurobi only accepts dense objective vectors, so just convert it before calling the interface. Also, I'd recommend using the solver-independent [linprog](http://mathprogbasejl.readthedocs.org/en/latest/linprog.html) interface, unless you have a good reason to tie yourself to gurobi.
