### ISSUE TITLE
What is the meaning of "rowinds", "colinds", "coeffs" in Example 2.2?

### ISSUE THREAD

**Issue by morvinzha** [JuliaOpt/Gurobi.jl#67]
Hi, I am trying to solve a MIQP problem and feel confused about some of your arguments... Could you please tell me what is the meaning of "rowinds", "colinds", "coeffs" in Example 2.2? Thank you very much in advance. :)

```
# add quadratic terms: x^2, x * y, y^2
# add_qpterms!(model, rowinds, colinds, coeffs)
add_qpterms!(model, [1, 1, 2], [1, 2, 2], [1., 1., 1.])
```

**Comment by mlubin** [comment]
There's no reason to use this Gurobi-specific API. You will find more documentation and support for using either MathProgBase or JuMP.

**Comment by morvinzha** [comment]
Aha, I see. Thanks for your reply!
