### ISSUE TITLE
Omission in Documentation?

### ISSUE THREAD

**Issue by gdowdy3** [JuliaOpt/Gurobi.jl#73]
I'm new to using Gurobi in Julia, so I was following your README, looking at the examples.  In particular, I was looking at Example 1.4.  I could run the code and solve the optimization problem, but I noticed that any parameters I attempted to manipulate through a combination of 

     env = Gurobi.Env()
and

     setparam!(env, name, v) 
had no effect on the results.

After more time than I care to admit, I realized that the problem was the following line in Example 1.4:

    m = Model(solver=GurobiSolver())
As soon as I updated this to read

    m = Model(solver=GurobiSolver(env))
My parameter manipulations had the expected effect.

For the seasoned Gurobi users out there, it is perhaps obvious that we somehow need to inform Gurobi of the changes made to the environment.  However, this was not obvious to a noob like me.  You might consider updating the troublesome line in Example 1.4 to spare future noobs the same confusion.

**Comment by mlubin** [comment]
Happy to consider pull requests. We receive no support from Gurobi for maintaining this package.

**Comment by odow** [comment]
There is a brief mention about sharing `env`'s right at the bottom of the readme. Maybe it just needs to be made more explicit.

@gdowdy3 you can edit the readme in Github by navigating to https://github.com/JuliaOpt/Gurobi.jl/blob/master/README.md and clicking the pencil icon on the top right of the file.
