### ISSUE TITLE
set_intattr! not working

### ISSUE THREAD

**Issue by cossio** [JuliaOpt/Gurobi.jl#85]
Suppose I create a `Gurobi.Model`, called `m`. Then I do this:

```julia
Gurobi.set_intattr!(model, "NumObj", 10)
Gurobi.get_intattr(model, "NumObj")
```

Interestingly, the last line returns `1`, instead of `10`. Why is `NumObj` not being modified here?

**Comment by cossio** [comment]
Another related example:

```julia
env = Gurobi.Env()
A = [1. 1.]
lb = [0.; 0.]
b = [1.]
f = [1.; 1.]
model = gurobi_model(env, name = "My Model", sense = :maximize, A = A, b = b, lb = lb, f = f)
@show model_sense(model)
Gurobi.set_sense!(model, :minimize)
@show model_sense(model)
```

Here `set_sense!` (which calls `set_intattr!`) also has no effect.

**Comment by joehuchette** [comment]
You likely have to call ``update_model!(model)`` to update the model state with Gurobi.

**Comment by cossio** [comment]
@joehuchette Oh! thanks. Silly mistake.

**Comment by joehuchette** [comment]
Don't sweat it, this is somewhat obscure.
