### ISSUE TITLE
Large coefficients

### ISSUE THREAD

**Issue by odow** [JuliaOpt/Gurobi.jl#94]
As raised [here](https://github.com/JuliaOpt/Gurobi.jl/issues/60#issuecomment-288571797), when setting the objective Gurobi silently rounds numbers greater than 1e100 down to 1e100.

```julia
using JuMP, Gurobi
m = Model(solver=GurobiSolver())
@variable(m, x >= 1)
@objective(m, Min, 1.1e100 * x)
solve(m) # :Optimal
getobjectivevalue(m) # 1.0e100 not 1.1e100
```
This also happens when setting other values such as the RHS. This is probably because Gurobi just rounds inputs to GRB_INFINITY (1e100).

Things also get weird around variable bounds. It ignores variable bounds larger than or equal to 1e20 (when +ve and upper, or -ve and lower)
```julia
using JuMP, Gurobi
m = Model(solver=GurobiSolver())
@variable(m, x <= 1e20)
@objective(m, Min, x)
solve(m) # unbounded
# ... or ...
# @variable(m, x >= -1e20)
# @objective(m, Max, x)
```

But when -ve and upper or +ve and lower, it allows up to 1e30
```julia
using JuMP, Gurobi
m = Model(solver=GurobiSolver())
@variable(m, x >= 1e30)
@objective(m, Min, x)
solve(m) # infeasible (default upper bound is 1e30)
# ... or
@variable(m, x <= -1e30)
@objective(m, Max x)
```

These "features" are also present in the Python interface.

Not really sure what we should do about it.

**Comment by odow** [comment]
cc @mburq

**Comment by odow** [comment]
Gurobi confirm that this is expected behaviour:
https://groups.google.com/forum/#!topic/gurobi/M_Bzc6RWMhU

**Comment by blegat** [comment]
It seems that we should do a warning from the Julia wrapper. It might be very helpful and I don't think that it would give a noticeable performance overhead.
