### ISSUE TITLE
I am not able to optimize models using gurobi. I have the license version 7.0.2 and Julia 0.5.1/ can you help me out. I have captured error message.

### ISSUE THREAD

**Issue by gpinu1** [JuliaOpt/Gurobi.jl#97]

**Comment by gpinu1** [comment]
![image](https://cloud.githubusercontent.com/assets/26877935/24716856/9f0b9dea-19ed-11e7-8fbc-7147dff7bfb0.png)

**Comment by gpinu1** [comment]
![image](https://cloud.githubusercontent.com/assets/26877935/24716909/c71afd4e-19ed-11e7-9821-5318e9156338.png)

**Comment by joehuchette** [comment]
Did you try what the error message suggests? Make sure you've also read https://github.com/JuliaOpt/Gurobi.jl#installation

**Comment by gpinu1** [comment]
I have gone through the instructions even with environmental variable path  and  I have installed gurobi with license key(7.0.2). can you help me with this issue. I want to completely migrate opl studio programming from Cplex opl studio to gurobi(jump model) with Julia.

**Comment by joehuchette** [comment]
What's the complete output from ``Pkg.build("Gurobi")`` and ``@show ENV["GUROBI_HOME"]``?

**Comment by gpinu1** [comment]
![image](https://cloud.githubusercontent.com/assets/26877935/24722637/b8a98bcc-1a01-11e7-9fda-1742fdcaa11c.png)

**Comment by joehuchette** [comment]
The environment variable isn't set properly. Make sure it is, then run ``Pkg.build("Gurobi")`` again.

**Comment by gpinu1** [comment]
![image](https://cloud.githubusercontent.com/assets/26877935/24722942/ca991e14-1a02-11e7-933e-bf22efd91c96.png)

**Comment by gpinu1** [comment]
Is ti correct with environment variable setting and building package

**Comment by odow** [comment]
`GUROBI_HOME` should be something like `C:\\gurobi700\\win64`

**Comment by gpinu1** [comment]
I am still getting same error with changed variable.
![image](https://cloud.githubusercontent.com/assets/26877935/24724982/6f5aeaca-1a0a-11e7-8255-70d737048b87.png)
![image](https://cloud.githubusercontent.com/assets/26877935/24725110/d8f542e6-1a0a-11e7-87bb-38458b06ce7b.png)

**Comment by odow** [comment]
Close Julia and reopen it. The environment variable should probably not have the `\bin\` at the end either.

**Comment by gpinu1** [comment]
Sorry to trouble you. It shows the same issue. can you help me out.
![image](https://cloud.githubusercontent.com/assets/26877935/24725661/fdb3b700-1a0c-11e7-90d4-4b74a604621c.png)
![image](https://cloud.githubusercontent.com/assets/26877935/24725857/85f0768a-1a0d-11e7-855a-440f35cc609b.png)

**Comment by odow** [comment]
Did you fully close Julia? Not just the notebook tab?

Does any other environment variable work?

What is the output of `@show ENV["Path"]`?

**Comment by gpinu1** [comment]
i HAVE CLOSED JULIA I NOTEBOOK TAB.
I do not have any other environmental variable work now
![image](https://cloud.githubusercontent.com/assets/26877935/24726901/36ca55e0-1a11-11e7-80aa-58e81edf60e8.png)
the output is:
![image](https://cloud.githubusercontent.com/assets/26877935/24726764/c14a7c5a-1a10-11e7-9082-126bf5e842d1.png)

**Comment by odow** [comment]
Close all of IJulia and open a (fresh) Julia command line (which looks as though it might be in `C:/Julia/bin/julia.exe`).

Then run the commands below and show the output.

![juliahelp](https://cloud.githubusercontent.com/assets/8177701/24727197/502ae430-1aa9-11e7-9f15-6e95310daca9.png)

**Comment by joehuchette** [comment]
This is not a Gurobi.jl issue, I would consult a site like Stackoverflow to resolve this.

**Comment by gpinu1** [comment]
![image](https://cloud.githubusercontent.com/assets/26877935/24728688/383287ac-1a18-11e7-9f3f-a53456f2eda4.png)

**Comment by gpinu1** [comment]
![image](https://cloud.githubusercontent.com/assets/26877935/24729833/49798aba-1a1d-11e7-9503-4c5dfb337b72.png)

**Comment by gpinu1** [comment]
![image](https://cloud.githubusercontent.com/assets/26877935/24730506/3fa216de-1a21-11e7-8aca-33fe72240b7f.png)
